name: Publish to @next

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ci
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'refs/heads/main'
    steps:
      - run: echo "${{ toJson(github.event.workflow_run) }}"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Add changeset that bumps all public packages
        # There needs to be a changeset for each package to publish.
        run: cp .github/changeset-samples/patch-all.md .changeset 
      - name: Run changeset version to next tag
        run: yarn changeset version --snapshot next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to next tag
        run: yarn changeset publish --tag next