name: Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }}"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test packages
        run: yarn test
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash      