name: Tests

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repo:
        required: true
        type: string
    secrets:
      USERNAME:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "mocking setup stage..."
  unit:
    runs-on: ubuntu-latest
    needs: setup
    environment: CI
    strategy:
      matrix:
        package:
          - core
          - bar
          - foo

    steps:
      - name: echo ref
        run: echo ${{ inputs.ref }}
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}
          persist-credentials: false
      - run: git log
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "yarn"
      - name: Check if CI environment is accessible
        run: echo ${{ secrets.USERNAME }}
      - name: Check if repo secret is accessible
        run: echo ${{ secrets.NOT_SECRET }}
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Build packages
        run: yarn ${{ matrix.package }} build
      - name: Test packages
        run: yarn ${{ matrix.package }} test
      - run: sleep 17s
        shell: bash
